version: '3'
services:
    money-mate:
        image: cheesed:latest
        expose:
            - "3000"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:443"
        depends_on:
            - money-mate
